---
extends: default

rules:
  line-length:
    max: 200  # Lenient for CI/CD files with long command lines
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'True', 'False']
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

ignore: |
  .github/
  .venv/
  node_modules/
  dist/
  build/
  *.egg-info/
